name: learn-github-actions
run-name: Build repository
on: [push]
jobs:
  build:
    stage: build
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./.ci/build_repository.sh
      - run: ./.ci/build_repository.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with: 
          name: mcap-wrapper-build
          path: |
              lib
              include
  create_installer:
    stage: build
    needs: build
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: mcap-wrapper-build
      - name: Add permission for executing the installer script
        run: chmod +x ./.ci/build_installer.sh
      - name: Execute create installer script
        run: cd ./.ci && ./build_installer.sh


