name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev 
      - run: sudo apt install libopencv-dev opencv-python
      - run: sudo apt install libwebsocketpp-dev
      - run: chmod +x ./.ci/build_repository.sh
      - run: ./.ci/build_repository.sh
