name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./.ci/build_repository.sh
      - run: ./.ci/build_repository.sh
