name: learn-github-actions
run-name: ${{ github.event.head_commit.message }} CI/CD
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./.ci/build_repository.sh
      - run: ./.ci/build_repository.sh
      - name: Add permission for executing the installer script
        run: chmod +x ./.ci/build_installer.sh
      - name: Execute create installer script
        run: cd ./.ci && ./build_installer.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with: 
          name: mcap-wrapper-build
          path: |
              lib
              include
              cmake
              build
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with: 
          name: mcap-wrapper-installer
          path: .ci/install_dependencies/install_mcap_wrapper
  test:
    needs: build
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Add repository
        run: git config --global --add safe.directory /__w/MCAPWrapper/MCAPWrapper
      - name: checkoutLFS
        run: git lfs pull
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: mcap-wrapper-build
      - name: Install
        run: cd build && make install && cd ..
      - name: UNIT test
        run: cd tests && chmod +x run.sh && ./run.sh

