name: learn-github-actions
run-name: ${{ github.event.head_commit.message }} CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./.ci/build_repository.sh
      - run: ./.ci/build_repository.sh
      - name: Add permission for executing the installer script
        run: chmod +x ./.ci/build_installer.sh
      - name: Execute create installer script
        run: cd ./.ci && ./build_installer.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with: 
          name: mcap-wrapper-installer
          path: .ci/install_dependencies/install_mcap_wrapper
  test:
    needs: build
    runs-on: ubuntu-latest
    container: tanguyhardelin/ubuntu-with-opencv:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: mcap-wrapper-installer
      
      - name: UNIT test
        run: cd tests && chmod +x run.sh && ./run.sh

